/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: "class",
    content: [
        "./pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./components/**/*.{js,ts,jsx,tsx,mdx}",
        "./app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            colors: {
                "inverse-surface": "#fcf8ff",
                "on-surface": "#e9e6f7",
                "inverse-primary": "#842cd3",
                "surface-variant": "#242434",
                "surface-tint": "#cc97ff",
                "error-dim": "#d73357",
                "on-tertiary-fixed": "#050061",
                "secondary-fixed": "#ffc1d6",
                "surface-container-low": "#12121e",
                "secondary-dim": "#ff67ad",
                "surface": "#0d0d18",
                "surface-container-lowest": "#000000",
                "surface-container-high": "#1e1e2d",
                "primary": "#cc97ff",
                "primary-fixed": "#c284ff",
                "surface-bright": "#2b2a3c",
                "on-primary-fixed-variant": "#430076",
                "surface-dim": "#0d0d18",
                "surface-container-highest": "#242434",
                "primary-container": "#c284ff",
                "on-tertiary-container": "#000000",
                "outline-variant": "#474754",
                "on-primary": "#47007c",
                "secondary-container": "#aa0266",
                "on-secondary-fixed": "#6b003e",
                "on-primary-container": "#360061",
                "tertiary": "#9093ff",
                "on-background": "#e9e6f7",
                "on-secondary-fixed-variant": "#9e005e",
                "primary-dim": "#9c48ea",
                "tertiary-container": "#7073ff",
                "on-error-container": "#ffb2b9",
                "inverse-on-surface": "#555461",
                "on-tertiary": "#080079",
                "surface-container": "#181826",
                "outline": "#757482",
                "on-surface-variant": "#aba9b9",
                "tertiary-fixed": "#a6a9ff",
                "tertiary-dim": "#6063ee",
                "error": "#ff6e84",
                "error-container": "#a70138",
                "secondary-fixed-dim": "#ffaccb",
                "tertiary-fixed-dim": "#9699ff",
                "primary-fixed-dim": "#b971ff",
                "on-secondary-container": "#ffe5ec",
                "on-primary-fixed": "#000000",
                "on-tertiary-fixed-variant": "#1e18b2",
                "on-secondary": "#460027",
                "secondary": "#ff67ad",
                "background": "#0d0d18",
                "on-error": "#490013"
            },
            fontFamily: {
                "headline": ["Plus Jakarta Sans"],
                "body": ["Manrope"],
                "label": ["Manrope"]
            },
            borderRadius: { "DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px" },
        },
    },
    plugins: [],
}